### ISSUE TITLE
Cut by layers / color

### ISSUE THREAD

**Issue by frmdstryr** [inkcut/inkcut#126]

**Comment by Franck78** [comment]
Oh please, add this one, filter out by layers first !

Just do easy : a new vertical Tab under WeedLines named "Layers"
Then display in it layer's names with a checkbox !

I use Inkscape to repaint my old pinball cabinet . 
Each color is a stencil mask, 2 or 3 layers,  more for a backglass

Color is good for selecting a tool but remember there is not a lot of cutter with multitool head (yes common Caméo have two tools), but still ;)

Thank you
 Franck

**Comment by frmdstryr** [comment]
In  #254 if anyone would like to test.
