### ISSUE TITLE
crashes at device setup

### ISSUE THREAD

**Issue by lgroc** [inkcut/inkcut#163]
i'm trying to setup a Creation pcut cs-1200 with serial port but it crashes instantly at setup or refreshing port.

OS: windows 7 x32

log: [inkcut.txt](https://github.com/codelv/inkcut/files/3171097/inkcut.txt)

**Comment by frmdstryr** [comment]
Is there a `crash.txt` in the log folder?

**Comment by lgroc** [comment]
no, only inkcut.txt

**Comment by frmdstryr** [comment]
Unfortunately I can't see anything in the log... Does it output any error message that is not reported in the log?

You can try to update to the latest version with  `pip3 install git+https://github.com/codelv/inkcut.git` there was one change related to printers that may have been the issue.

**Comment by Bargud** [comment]
Good day,

I would like to ask if you already solve this problem because I have same issue. Once I opened device settings incut crash without any crash log, only incut.txt
If I do same thing with plotter disconnected from computer there is no issue.

I'm using version - v2.2.1

Thank you
