### ISSUE TITLE
Inkcut - Workspace start up error

### ISSUE THREAD

**Issue by DrBwts** [inkcut/inkcut#176]
Just installed Inkcut & run it from the command line & go this error...

![image](https://user-images.githubusercontent.com/22524334/60344684-fc6ef480-99ae-11e9-9ba6-50e37e3ad7eb.png)

Running on Win10 x64 installed using pip install inkcut as I couldnt get pip3 to work

**Comment by frmdstryr** [comment]
The master branch has fixes for these errors on python 2. Try updating with

`pip install git+https://github.com/inkcut/inkcut.git`

**Comment by DrBwts** [comment]
Yes working now altough I can find my device in the device setup, Pixmax 720. Should I open a new thread?

**Comment by raboof** [comment]
> I cant find my device in the device setup, Pixmax 720. Should I open a new thread?

Yes I think that would be best!
