### ISSUE TITLE
Inkcut 2 dependency problem (resolution inside !!) [python-setuptools][python setup.py egg_info]

### ISSUE THREAD

**Issue by AlexCalibur** [inkcut/inkcut#191]
Hi, about inkcut V2, with instruction from https://www.codelv.com/projects/inkcut/docs/installing an error is reported during the 
 _pip3 install inkcut_

Result : 
```
Complete` output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dsov070v/pyqtgraph/
```

Then, _# aptitude install python-setuptools_ doesn't solve it !! 

But, _#aptitude install python**3**-setuptools_  do the job, and no more error on it ;)

So, I think you can add this package to 'Install dependencies' chapter ;)

**Comment by frmdstryr** [comment]
Thanks added this.
