### ISSUE TITLE
[packaging] Missing translation files

### ISSUE THREAD

**Issue by aaujon** [inkcut/inkcut#195]
When installing inkcut from pip3, the translation files are missing, they should be located under : /usr/local/lib/python3.7/site-packages/inkcut/res/translations

**Comment by frmdstryr** [comment]
Thanks, this is fixed in https://github.com/inkcut/inkcut/commit/8234cc997e26c3b2a6462f6477130f6ecbe47109 and will be in the next release

**Comment by aaujon** [comment]
great thanks !
