### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by AntoineTurmel** [inkcut/inkcut#201]
I have installed Inkut 2.1.0 using pip on a french version of Windows 10 (x64).
But the software remain in English.
How do I switch to french ? I have notice the InkCut folder was missing res/translations :

C:\Users\Antoine\AppData\Local\Programs\Python\Python37\Lib\site-packages\inkcut\res\

I did add the translations folder along with fr_FR files, but it's still in english.

**Comment by AntoineTurmel** [comment]
Just to be sure, I have verified this:
```
>>> import enaml
>>> from enaml.qt import QT_API, QtCore, QtWidgets, QtGui
>>> QtCore.QLocale.system().name()
'fr_FR'
```

**Comment by Crepin1989** [comment]
![15775487509705980242638431900705](https://user-images.githubusercontent.com/59314927/71546093-181d7c80-298b-11ea-8539-21f11be3b2ed.jpg)
I installed Inkscape and the extension of Inkcut. When I want to cut out something, the extension does not open.

**Comment by Crepin1989** [comment]
"Traceback (most recent call last):
  File "inkcut_cut.py", line 73, in <module>
    effect.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "inkcut_cut.py", line 67, in effect
    close_fds=True)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 278, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr"

I have the text above as comment, but the extension does not link my computer to Inkcut. 

What should do? I use Windows Pro 10, the French version. 

Thanks for any proposal of solution.

**Comment by aaujon** [comment]
Hi, about the language issue, I believe it has been fixed in 8234cc9, the issue was reported in bug #195

**Comment by aaujon** [comment]
Can you try again with the latest developpement version ?

**Comment by aaujon** [comment]
@frmdstryr you can close this

**Comment by Crepin1989** [comment]
Hello Sir, please can I send AnyDesk to you so that you install Inkcut on
my computer?

I tried many times, but unfortunately I didn't succeed.

Have a Nice Day!

Le mer. 29 juil. 2020 à 16:11, frmdstryr ***@***.***> a
écrit :
