### ISSUE TITLE
App crash if empty working area

### ISSUE THREAD

**Issue by vmario89** [inkcut/inkcut#224]
![grafik](https://user-images.githubusercontent.com/5631071/73602304-058df880-4572-11ea-8448-d33aeed117c8.png)

hi, if view is empty and pressing the left button will let inkcut crash with following statement
`2020-02-02 04:08:12,804 | CRITICAL | inkcut | integer division or modulo by zero`
**pressing the right button will crash without any error in log files**

**Comment by frmdstryr** [comment]
Thanks for reporting this. It should be fixed now.

**Comment by aaujon** [comment]
I can confirm that this issue is fixed.

**Comment by aaujon** [comment]
@frmdstryr you can close this issue
