### ISSUE TITLE
ModuleNotFoundError: No module named 'atom.compat'

### ISSUE THREAD

**Issue by flying4fun** [inkcut/inkcut#238]
After installing via pip3, I get the following on both Linux (Fedora Core 31) and microsoft 10.
`ModuleNotFoundError: No module named 'atom.compat'`

I cannot find any info about atom.compat anywhere.  Didn't get any errors during the install via pip.

**Comment by flying4fun** [comment]
```
$ pip3 list|grep atom
atom               0.5.0

$ pip3 list|grep enaml 
enaml              0.10.4    
enamlx             0.4.1    
```

I assume it's part of enaml since I get the following:

`  File "/usr/local/lib64/python3.7/site-packages/enaml/compat.py", line 11, in <module>
    from atom.compat import *
ModuleNotFoundError: No module named 'atom.compat'
`

**Comment by chulo601** [comment]
im having the same problem with ModuleNotFoundError: No module named 'atom.compat' so if you solve the problem can you please post it. thank you

**Comment by frmdstryr** [comment]
Run `pip install atom==0.4.3` the new release drops python 2 support and apparently breaks every old version of enaml...

**Comment by chulo601** [comment]
thanks @frmdstryr it work for ubuntu but on windows get a error NameError: name 'BREAK_LOOP' is not defined

**Comment by frmdstryr** [comment]
You can either downgrade to python 3.7 and reinstall everything (with atom==0.4.3) or if you want to use python 3.8, you'll need to upgrade back to `atom==0.5.0` then install enaml from the master branch on github (or wait until enaml is released).

**Comment by chulo601** [comment]
thanks again. i will test it tomorrow to see if it works on windows,

**Comment by MatthieuDartiailh** [comment]
The new release of enaml compatible with ataom 0.5.0 is now available on PyPI.

**Comment by flying4fun** [comment]
Very good!  Thanks for the quick reply.  I was about to try to start downgrading some of the modules until I got it working.  

I have verified that the updated enaml is indeed compatible with atom 0.5.0 and now inkcut works.  
(pip3 install enaml --upgrade)

Thanks again!

**Comment by chulo601** [comment]
ok thanks @MatthieuDartiailh

**Comment by chulo601** [comment]
I upgrade the enaml on windows an now i get AttributeError: module 'time' has no attribute 'clock' on windinws 10

**Comment by frmdstryr** [comment]
Please create a new issue with the full error.
