### ISSUE TITLE
Quick switch between plotter/cutter

### ISSUE THREAD

**Issue by Franck78** [inkcut/inkcut#256]
Hi frmdstryr ,

Sound silly but probably  you some can (I do) use the plotter to plot or cut.

There is one absolute mandatory setting to change every time, the offset of the blade (to have square corners).

Because it is hidden, not easily memorized (the value), etc etc etc it would be cool if:

A big always visible switch allows changing setup from "Cutter<=>Plotter" profile

Perhaps also some other settings can be swapped (speed?), tool to use...

**Comment by frmdstryr** [comment]
If I remember correctly the code is already there for this but the user interface needs changed to support this.

**Comment by frmdstryr** [comment]
Actually I think its already possible to so this using the dropdown in the monitor tab (though there probably should be a more obvious way to change devices)

**Comment by Franck78** [comment]
I think so, but not sure.
The essential param for my problem is in a Filter

There is Class for the parameters (Offset,Angle) , Instanciated  (config=Intanciate(params) )
in another Filter class, filter registered with the Devive class.....

Problem, I don't understant of to pass a param from to the filter to select between some config.

**Comment by frmdstryr** [comment]
@Franck78 I added this. The device setup now supports saving multiple device configurations and you can select one by either choosing it in the settings or selecting it in the Control or Monitor rabs. Please give it a try.

![image](https://user-images.githubusercontent.com/380158/88462779-ecf50000-ce7b-11ea-9802-38d56b8a7c41.png)

**Comment by frmdstryr** [comment]
Please create a new issue if you find any with this. Thanks for the suggestion!

**Comment by Franck78** [comment]
I will use inkcut soon. Just ordering tasks ;)

Franck
