### ISSUE TITLE
Font color not feasible with Mac OSX dark theme

### ISSUE THREAD

**Issue by DanielYWoo** [inkcut/inkcut#299]
The UI looks great with Light theme, but difficult to read in Dark theme.

![Screen Shot 2020-12-21 at 6 18 21 PM](https://user-images.githubusercontent.com/514417/102766348-f3e75680-43b8-11eb-85a9-b3d2dfd7b885.png)

**Comment by frmdstryr** [comment]
Try the system theme

**Comment by DanielYWoo** [comment]
works! thanks for the quick help. BTW, could you set "system" schema as default?
