### ISSUE TITLE
g-code output does not use decimals

### ISSUE THREAD

**Issue by risacher** [inkcut/inkcut#301]
I am trying to output to a device that uses G-code measured in millimetres (a Sainsmart Genmitsu), but the Inkcut g-code output protocol seems to only use integer outputs, which is insufficiently precise.  Possibly tie into #174

**Comment by frmdstryr** [comment]
See https://github.com/inkcut/inkcut/blob/master/inkcut/device/protocols/gcode.py#L18

If you change the `%i` to `%f` for the X and Y it'll output floats, probably need to round to whatever it precision you need.
