### ISSUE TITLE
Live preview shows measurements in inches when units are set to mm

### ISSUE THREAD

**Issue by TriploidTree** [inkcut/inkcut#319]
Inkcut version 2.1.3 on Linux mint 20.2

What happens:
- When inkcut is set to mm, the graphic size is correctly displayed in mm.
- When "send to print" is selected the graphic size is show in inches with inch units.
- In the line view, the measurements are in inches but show mm units.

What should happen:
When Inkcut when inkcut is set to mm, all measurement should be displayed in mm, with correct units.

![image](https://user-images.githubusercontent.com/4170521/139885833-bfed092d-9479-4d3d-9d85-9cfa648fe612.png)

**Comment by vikingsraven** [comment]
Hi seeing this on windows 10 as well, Graptech 5000 config used for graptech craft robo pro
![image](https://user-images.githubusercontent.com/11271233/179391567-de50b557-08a2-44b9-8eac-83b13bdcdff1.png)
