### ISSUE TITLE
ImportError PYSIDE_API; QtPy 2.0.0 breaks InkCut + Workaround

### ISSUE THREAD

**Issue by suuppl** [inkcut/inkcut#321]
With [QtPy Version 2.0.0](https://github.com/spyder-ide/qtpy/releases/tag/v2.0.0), the support for the qt4 api was dropped, so inkcut crashes on start with an ImportError 
```ImportError: cannot import name 'PYSIDE_API' from 'qtpy' (/usr/local/lib/python3.9/dist-packages/qtpy/__init__.py)```

The workaround to get it to work (on windows 11, probably also on other systems) is to install qtpy 1.11.3 
```bash 
pip3 uninstall qtpy
```
```bash
pip3 install qtpy==1.11.3
```

**Comment by frmdstryr** [comment]
This was fixed in enamlx
