### ISSUE TITLE
device-setup documentation page is missing on site

### ISSUE THREAD

**Issue by matthijskooijman** [inkcut/inkcut#330]
The README links to https://www.codelv.com/projects/inkcut/docs/device-setup but that gives me a 404.

The documentation is present in the repo here: https://github.com/inkcut/inkcut/blob/master/docs/device-setup.md

So I guess something in the docs build process omits this file, maybe because of the dash?

**Comment by frmdstryr** [comment]
Ah... sorry. I updated my site and it no longer does blocking requests to github to update anymore.  It should be there now. Thanks!

**Comment by matthijskooijman** [comment]
Works, thanks!
