### ISSUE TITLE
Can only cut smaller than 207mm

### ISSUE THREAD

**Issue by theresistance2** [inkcut/inkcut#333]
I'm on a MacBook Pro 2020 M1 and a "Masterplott DG720", a Roland CX24 clone.

When I try to cut something wider than 207mm the cutting head moves over like it would start and then just return back to origin. I can see packets being transmitted via serial, but the machine ignores it. When I resize the layout to something smaller than 207mm, it cuts perfectly. 

The other thing is that the machine always ignores the last command, but my workaround is to create weedlines, it only "forgets" about the last weedline then.

**Comment by frmdstryr** [comment]
>  a Roland CX24 clone.

What do you expect? Contact the manufacturer.
