### ISSUE TITLE
inkscape extension no longer works with Inkscape 1.2

### ISSUE THREAD

**Issue by raboof** [inkcut/inkcut#339]
In Inkscape 1.2, the deprecated `inkex.py` that we use for the inkscape extension has been removed (https://gitlab.com/inkscape/extensions/-/merge_requests/460)

**Comment by FabLabBaramati** [comment]
is any solution to work with Inkscape 1.2 ?

**Comment by raboof** [comment]
> is any solution to work with Inkscape 1.2 ?

Yes, it works with the change in #340
