### ISSUE TITLE
Inkcut Forum page

### ISSUE THREAD

**Issue by zimbot-one** [inkcut/inkcut#375]
Hello, i dont know if you are also running the forum page on inkcut.org. If so, I would like to report that something with your email servers certificate is wrong. When requesting an approval link for my new account my postfix SMTP reports the following:

`Apr  4 15:24:05 server1 postfix/smtpd[546434]: setting up TLS connection from unknown[109.205.61.198]
Apr  4 15:24:05 server1 postfix/smtpd[546434]: unknown[109.205.61.198]: TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH:!ECDHE-RSA-RC4-SHA"
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:before SSL initialization
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:before SSL initialization
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:SSLv3/TLS read client hello
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:SSLv3/TLS write server hello
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:SSLv3/TLS write change cipher spec
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:TLSv1.3 write encrypted extensions
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:SSLv3/TLS write certificate
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:TLSv1.3 write server certificate verify
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:SSLv3/TLS write finished
Apr  4 15:24:05 server1 postfix/smtpd[546434]: SSL_accept:TLSv1.3 early data
Apr  4 15:24:06 server1 postfix/smtpd[546434]: SSL3 alert read:fatal:bad certificate
Apr  4 15:24:06 server1 postfix/smtpd[546434]: SSL_accept:error in error
Apr  4 15:24:06 server1 postfix/smtpd[546434]: SSL_accept error from unknown[109.205.61.198]: -1
Apr  4 15:24:06 server1 postfix/smtpd[546434]: warning: TLS library problem: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42:
Apr  4 15:24:06 server1 postfix/smtpd[546434]: lost connection after STARTTLS from unknown[109.205.61.198]
Apr  4 15:24:06 server1 postfix/smtpd[546434]: disconnect from unknown[109.205.61.198] ehlo=1 starttls=0/1 commands=1/2
`
Can you have a look on this so i can participate in the forum ?
MTIA

**Comment by frmdstryr** [comment]
Thanks, its likely the cert was not renewed again. Seems others are able to join now.
